/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as WidgetSlugRouteImport } from './routes/widget.$slug'
import { Route as AuthenticatedLayoutsNewRouteImport } from './routes/_authenticated/layouts/new'
import { Route as AuthenticatedTestimonialsIndexRouteImport } from './routes/_authenticated/testimonials/index'
import { Route as AuthenticatedTestimonialsIdRouteImport } from './routes/_authenticated/testimonials/$id'
import { Route as AuthenticatedTestimonialsNewRouteImport } from './routes/_authenticated/testimonials/new'
import { Route as AuthenticatedLayoutsIdIndexRouteImport } from './routes/_authenticated/layouts/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WidgetSlugRoute = WidgetSlugRouteImport.update({
  id: '/widget/$slug',
  path: '/widget/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutsNewRoute = AuthenticatedLayoutsNewRouteImport.update({
  id: '/layouts/new',
  path: '/layouts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestimonialsIndexRoute =
  AuthenticatedTestimonialsIndexRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestimonialsIdRoute =
  AuthenticatedTestimonialsIdRouteImport.update({
    id: '/testimonials/$id',
    path: '/testimonials/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestimonialsNewRoute =
  AuthenticatedTestimonialsNewRouteImport.update({
    id: '/testimonials/new',
    path: '/testimonials/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLayoutsIdIndexRoute =
  AuthenticatedLayoutsIdIndexRouteImport.update({
    id: '/layouts/$id/',
    path: '/layouts/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/$slug': typeof WidgetSlugRoute
  '/layouts/new': typeof AuthenticatedLayoutsNewRoute
  '/testimonials/$id': typeof AuthenticatedTestimonialsIdRoute
  '/testimonials/new': typeof AuthenticatedTestimonialsNewRoute
  '/testimonials/': typeof AuthenticatedTestimonialsIndexRoute
  '/layouts/$id/': typeof AuthenticatedLayoutsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/$slug': typeof WidgetSlugRoute
  '/layouts/new': typeof AuthenticatedLayoutsNewRoute
  '/testimonials/$id': typeof AuthenticatedTestimonialsIdRoute
  '/testimonials/new': typeof AuthenticatedTestimonialsNewRoute
  '/testimonials': typeof AuthenticatedTestimonialsIndexRoute
  '/layouts/$id': typeof AuthenticatedLayoutsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/$slug': typeof WidgetSlugRoute
  '/_authenticated/layouts/new': typeof AuthenticatedLayoutsNewRoute
  '/_authenticated/testimonials/$id': typeof AuthenticatedTestimonialsIdRoute
  '/_authenticated/testimonials/new': typeof AuthenticatedTestimonialsNewRoute
  '/_authenticated/testimonials/': typeof AuthenticatedTestimonialsIndexRoute
  '/_authenticated/layouts/$id/': typeof AuthenticatedLayoutsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/widget/$slug'
    | '/layouts/new'
    | '/testimonials/$id'
    | '/testimonials/new'
    | '/testimonials/'
    | '/layouts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/widget/$slug'
    | '/layouts/new'
    | '/testimonials/$id'
    | '/testimonials/new'
    | '/testimonials'
    | '/layouts/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/widget/$slug'
    | '/_authenticated/layouts/new'
    | '/_authenticated/testimonials/$id'
    | '/_authenticated/testimonials/new'
    | '/_authenticated/testimonials/'
    | '/_authenticated/layouts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WidgetSlugRoute: typeof WidgetSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/widget/$slug': {
      id: '/widget/$slug'
      path: '/widget/$slug'
      fullPath: '/widget/$slug'
      preLoaderRoute: typeof WidgetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/layouts/new': {
      id: '/_authenticated/layouts/new'
      path: '/layouts/new'
      fullPath: '/layouts/new'
      preLoaderRoute: typeof AuthenticatedLayoutsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testimonials/': {
      id: '/_authenticated/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof AuthenticatedTestimonialsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testimonials/$id': {
      id: '/_authenticated/testimonials/$id'
      path: '/testimonials/$id'
      fullPath: '/testimonials/$id'
      preLoaderRoute: typeof AuthenticatedTestimonialsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testimonials/new': {
      id: '/_authenticated/testimonials/new'
      path: '/testimonials/new'
      fullPath: '/testimonials/new'
      preLoaderRoute: typeof AuthenticatedTestimonialsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/layouts/$id/': {
      id: '/_authenticated/layouts/$id/'
      path: '/layouts/$id'
      fullPath: '/layouts/$id/'
      preLoaderRoute: typeof AuthenticatedLayoutsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLayoutsNewRoute: typeof AuthenticatedLayoutsNewRoute
  AuthenticatedTestimonialsIdRoute: typeof AuthenticatedTestimonialsIdRoute
  AuthenticatedTestimonialsNewRoute: typeof AuthenticatedTestimonialsNewRoute
  AuthenticatedTestimonialsIndexRoute: typeof AuthenticatedTestimonialsIndexRoute
  AuthenticatedLayoutsIdIndexRoute: typeof AuthenticatedLayoutsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLayoutsNewRoute: AuthenticatedLayoutsNewRoute,
  AuthenticatedTestimonialsIdRoute: AuthenticatedTestimonialsIdRoute,
  AuthenticatedTestimonialsNewRoute: AuthenticatedTestimonialsNewRoute,
  AuthenticatedTestimonialsIndexRoute: AuthenticatedTestimonialsIndexRoute,
  AuthenticatedLayoutsIdIndexRoute: AuthenticatedLayoutsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WidgetSlugRoute: WidgetSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
